### PR TITLE
added windows 64bit support

### PR DESCRIPTION
**Pull request by emekoi**
now choosenim can build 64 bit nim on windows.

### CODE REVIEW

**Comment by dom96** [comment]
It's not that simple :)

**Comment by emekoi** [comment]
true.

**Comment by emekoi** [comment]
@dom96?

**Comment by dom96** [comment]
Because choosenim installs a 32bit MINGW by the default

**Comment by emekoi** [comment]
so i would just need to add support for download 64bit mingw?

**Comment by dom96** [comment]
This PR already handles this too: https://github.com/dom96/choosenim/pull/63

**Comment by emekoi** [comment]
i guess i'll close this then.

**Comment by dom96** [comment]
Sorry :) Thank you for giving this a shot.

**Pull request closed without merging**
