### PR TITLE
'choosenim installed' shows Nim versions located in the toolchain folder

### PR DESCRIPTION
**Pull request by ThomasTJdev**
See all available Nim versions located in the toolchain folder.

### CODE REVIEW

**Comment by dom96** [comment]
I think this should simply be merged into ``show``, we don't need a new command for this. Please make the output ``git branch``-like.

**Comment by ThomasTJdev** [comment]
Thank you for feedback! I'll update the PR.

@genotrance, I really like the the idea of `list all available`, but that deserves a separate PR.

**Comment by ThomasTJdev** [comment]
**Ver 2** is now available in the PR.

**Comment by genotrance** [comment]
Given the currently selected version is already mentioned at the top, I don't think there's a need to show it again in the list below and highlighting it. Perhaps we need to update that output to state that it is the selected version?

It will also be nice to have some title for the list of selectable versions:

```
Available versions:
   0.19.0
   0.18.0
   #hash-truncated1
   #hash-truncated2...
```

**Comment by dom96** [comment]
I think it would be good to remove the "Version: ..." and add "Versions:\n" above the version list in place of it.

**Comment by ThomasTJdev** [comment]
I personally prefer **V3** even though it is redundant. I like the git branch look, but I think the current `choosenim show` view is more **smooth**.

### V3
choosenim_v7

### V4
choosenim_v5

### V5
choosenim_v6

**Comment by dom96** [comment]
v3 looks good

**Comment by narimiran** [comment]
> v3 looks good

Can this be merged, then?

**Pull request merged**
