### PR TITLE
Fix eraseLine exception in msys

### PR DESCRIPTION
**Pull request by genotrance**
Choosenim fails on Travis for devel on Windows.

### CODE REVIEW

**Comment by genotrance** [comment]
The exact same commit ran successfully on my Travis instance. Gosh.

https://travis-ci.org/genotrance/choosenim/builds/527930381

**Comment by dom96** [comment]
Shouldn't you fix eraseLine instead? Why would it raise that OSError?

**Comment by genotrance** [comment]
I'll debug that in Nim directly. This fix is needed regardless since eraseLine will fail in a nontty.

**Comment by dom96** [comment]
okay, might be a good idea to write a newline in case this fails then. Otherwise you'll get a super long line with thousands of progress bars, better to have one line each IMO.

**Pull request merged**
